---
all:
  children:
    hlh_ai_engine_egpu_k80:
      hosts:
        192.168.1.31:
          ansible_host: 192.168.1.31
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
