---
hlh_ai_engine_freetoken:
  hosts:
    freetoken:
      ansible_host: 192.168.1.40
      ansible_user: root
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519

  vars:
    ansible_python_interpreter: /usr/bin/python3
